#!/bin/sh

echo "Masukkan password MySQL (biasanya radius / radmon)"
read pass

if [ -d "/www/RadiusMonitor" ]; then
    rm -rf /www/RadiusMonitor
fi

if [ -d "/usr/share/RadiusMonitor" ]; then
    rm -rf /usr/share/RadiusMonitor
fi

sleep 1

git clone --depth 1 https://github.com/maizil41/RadiusMonitor.git /usr/share/RadiusMonitor

sleep 1

chmod +x /usr/bin/radmon-exec
chmod +x /usr/bin/radmon-log
chmod +x /usr/bin/radmon-kuota

sleep 1

ln -s /usr/share/RadiusMonitor /www/RadiusMonitor

sleep 1

mysql -u root -p"$pass" -e "CREATE DATABASE radmon CHARACTER SET utf8";
mysql -u root -p"$pass" -e "GRANT ALL ON radmon.* TO 'radmon'@'localhost' IDENTIFIED BY 'radmon' WITH GRANT OPTION";

sleep 1

cd /www/RadiusMonitor && mysql -u root -p"$pass" radmon < radmon.sql

sleep 1

(crontab -l; echo "* * * * * /usr/bin/radmon-kuota >/dev/null 2>&1") | crontab -
(crontab -l; echo "0 0 * * * find /www/RadiusMonitor/dist/pages/data/tmp -type f ! -name 'index.php' -exec rm -f {} +") | crontab -
