name: Build Packages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'luci/luci-app-radmon-php7/**'
      - 'luci/luci-app-radmon-php8/**'

jobs:
  build:
    name: ${{ matrix.package }} build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - tag: openwrt-21.02
            package: luci-app-radmon-php7
            arch: x86_64
          - tag: openwrt-23.05
            package: luci-app-radmon-php8
            arch: x86_64

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.tag }}
          PACKAGES: ${{ matrix.package }}
          NO_REFRESH_CHECK: true

      - name: Find
        run: |
          FILE_PATH=$(find -name "luci-app-radmon-*.ipk")
          echo "FILE_PATH=$FILE_PATH" >> $GITHUB_ENV
          echo -e "FILE_PATH path: $FILE_PATH"

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}-${{ matrix.tag }}
          path: ${{ env.FILE_PATH }}
